#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# TODO: support apk for alpine containers
if ! command -v apt-get &>/dev/null; then
    echo "apt-get is required"
    exit 1
fi

sudo apt-get update && sudo apt-get install -y \
    bat \
    curl \
    fish \
    git \
    jq \
    neovim \
    ripgrep \
    unzip

curl -sSLf https://astral.sh/uv/install.sh |
    env UV_INSTALL_DIR="$HOME"/.local \
        INSTALLER_NO_MODIFY_PATH=1 \
        sh

curl -sSLf https://get.chezmoi.io |
    sh -s -- -b "$HOME"/.local/bin

curl -sSLf https://starship.rs/install.sh |
    sh -s -- -b "$HOME"/.local/bin -y

"$HOME"/.local/bin/chezmoi apply
