local opt, g = vim.opt, vim.g
g.mapleader = " "
opt.shiftwidth = 4
opt.tabstop = 4
opt.softtabstop = 4
opt.expandtab = true
opt.number = true
opt.relativenumber = true
opt.scrolloff = 3
-- opt.colorcolumn = "80,88,120"
opt.completeopt = "menu,menuone,noinsert"
