tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
# Enable Windows-like alt-tab
cask "alt-tab"
# Chromium based browser
cask "arc"
# Desktop password and login vault
cask "bitwarden"
# Web browser
cask "firefox"
# Recursive's prebuilt text-editor-friendly files, including powerline glyphs
cask "font-recursive-code"
cask "font-space-mono"
# Developer targeted fonts with a high number of glyphs
cask "font-symbols-only-nerd-font"
# Game development engine
cask "godot"
# Free and open-source media player
cask "iina"
# HTTP and GraphQL Client
cask "insomnia"
# Smooths scrolling and set mouse scroll directions independently
cask "mos"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Collaboration platform for API development
cask "postman"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Music streaming service
cask "spotify"
# Messaging app with a focus on speed and security
cask "telegram"
# Unpacks archive files
cask "the-unarchiver"
# Open-source code editor
cask "visual-studio-code"
# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm"
