[
  apps/bat.nix
  apps/bitwarden.nix
  apps/direnv.nix
  apps/fish.nix
  apps/fzf.nix
  apps/git.nix
  apps/go.nix
  apps/lsd.nix
  apps/neovim.nix
  apps/nix-index.nix
  apps/node.nix
  apps/python.nix
  apps/rust.nix
  apps/ssh.nix
  apps/starship.nix
  apps/viddy.nix
  apps/wezterm.nix
  apps/zoxide.nix
  apps/zs.nix
]
